main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'

urlpatterns = [
    # /zpr/
    url(r'^$', views.LoginView.as_view(), name='login'),

    url(r'register/$', views.UserFormView.as_view(), name='register'),

    url(r'login/$', views.LoginView.as_view(), name='login'),

    url(r'logout/$', views.LogoutView.as_view(), name='logout'),
]

student/urls.py
from django.conf.urls import url

from main.methods import select_course
from . import views

app_name = 'student'

urlpatterns = [
    # /student/
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^select_course/(?P<course_id>[0-9]+)/$', select_course, name='select-course'),

]

student_inbox/urls.py
from django.conf.urls import url

from student_inbox.views import accept_project_team_message, reject_project_team
from . import views

app_name = 'student_inbox'

urlpatterns = [
    # /student/
    url(r'^$', views.InboxView.as_view(), name='index'),
    url(r'(?P<pk>[0-9]+)/accept', accept_project_team_message, name='team-accept'),
    url(r'(?P<pk>[0-9]+)/reject', reject_project_team, name='team-reject'),

]

student_projects/urls.py
from django.conf.urls import url

from student_projects import views
from student_projects.views import sing_to_project, CreateProjectTeamView, UserProjectTeamView

app_name = 'student_projects'

urlpatterns = [
    url(r'^$', views.ProjectsView.as_view(), name='projects'),
    url(r'(?P<pk>[0-9]+)/sign', sing_to_project, name='project-sign'),
    url(r'(?P<pk>[0-9]+)/create', CreateProjectTeamView.as_view(), name='project-create-team'),
    url(r'userTeam', UserProjectTeamView.as_view(), name='project-team-view'),

]

zpr/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^zpr/', include('main.urls')),
    url(r'^zpr/student/', include('student.urls')),
    url(r'^zpr/student/projects/', include('student_projects.urls')),
    url(r'^zpr/student/inbox/', include('student_inbox.urls')),
    url(r'^zpr/tutor/', include('tutor.urls')),
    url(r'^zpr/tutor/posts/', include('tutor_posts.urls')),
    url(r'^zpr/tutor/projects/', include('tutor_projects.urls')),
    url(r'^zpr/tutor/students/', include('tutor_students.urls')),
    url(r'^zpr/tutor/courses/', include('tutor_courses.urls')),
    url(r'^zpr/tutor/tutors/', include('tutor_tutors.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/models.py
from django.db import models

from main.models import Project, Course, UserInbox


class ProjectTeam(models.Model):
    project = models.ForeignKey(Project)
    accepted = models.BooleanField(default=False)
    course = models.ForeignKey('main.Course', null=True)


class StudentUser(models.Model):
    profile = models.ForeignKey('main.UserProfile')
    album_number = models.CharField(max_length=16)
    eres_id = models.CharField(max_length=16)
    status = models.BooleanField
    group = models.CharField(max_length=32)
    courses = models.ManyToManyField(Course)
    projectTeams = models.ManyToManyField(ProjectTeam)
    signedProjects = models.ManyToManyField('main.Project')

    class Meta:
        db_table = 'student_user'

    def getCourseById(self, courseId):
        for course in self.courses.all():
            if course.id == courseId:
                return course
        return None

    def getSignedProjectForCourse(self, courseId):
        for project in self.signedProjects.all():
            if project.course.id == courseId:
                return project
        return None

    def setSignedProjectForCourse(self, project, courseId):
        alreadySignedProject = self.getSignedProjectForCourse(courseId)
        if alreadySignedProject is not None:
            self.signedProjects.remove(alreadySignedProject)
        self.signedProjects.add(project)
        self.save()

    def removeSignedProjectForCourse(self, courseId):
        alreadySignedProject = self.getSignedProjectForCourse(courseId)
        if alreadySignedProject is not None:
            self.signedProjects.remove(alreadySignedProject)
            self.save()

    def getProjectTeamForCourse(self, courseId):
        for team in self.projectTeams.all():
            if team.course.id == courseId:
                return team
        return None

    def setProjectTeamForCourse(self, projectTeam, courseId):
        alreadyAssignedProjectTeam = self.getProjectTeamForCourse(courseId)
        if alreadyAssignedProjectTeam is not None:
            self.projectTeams.remove(alreadyAssignedProjectTeam)
        self.projectTeams.add(projectTeam)
        self.save()

    def removeProjectTeamForCourse(self, courseId):
        alreadyAssignedProjectTeam = self.getProjectTeamForCourse(courseId)
        if alreadyAssignedProjectTeam is not None:
            self.projectTeams.remove(alreadyAssignedProjectTeam)
            self.save()

    def isStudentSignedToCourseProjectTeam(self, courseId):
        alreadyAssignedProjectTeam = self.getProjectTeamForCourse(courseId)
        if alreadyAssignedProjectTeam is not None and alreadyAssignedProjectTeam.accepted:
            return True
        else:
            return False

    def getStudentInboxOrCreateIfNone(self):
        if self.profile.inbox is None:
            UserInbox.objects.get_or_create(user_profile=self.profile)
            inbox = UserInbox.objects.get(user_profile=self.profile)
            self.profile.inbox = inbox
            self.profile.save()
        return self.profile.inbox

student/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View

from main.permissions import has_student_permissions
from main_posts.models import Post
from student.methods import getStudentUserFromRequest
from student_inbox.methods import refreshInboxStatus


class IndexView(View):
    template_name = 'student/index.html'
    login_url = 'main:login'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if has_student_permissions(request.user):
            return super(IndexView, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseForbidden('User has no access rights for viewing this page')

    def get(self, request):
        posts = []
        selectedCourseId = request.session.get('selected_course_id')
        if selectedCourseId is not None:
            try:
                posts = Post.objects.filter(course=selectedCourseId).order_by('-creation_time')
            except Post.DoesNotExist:
                pass
        else:
            posts = Post.objects.all().order_by('-creation_time')

        student = getStudentUserFromRequest(request)
        studentCourses = student.courses.all()
        request.session['courses'] = studentCourses
        refreshInboxStatus(request, student)
        return render(request, self.template_name, {'nbar': 'home', 'posts': posts})

student/templates/student/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ZPR</title>
    <!-- Loads the path you static files -->
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}"/>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"
               href="{% url 'student:index' %}">{{ request.session.selected_course_shortname }}</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Wybór przedmiotu<span
                            class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        {% if request.session.courses %}
                            {% for course in request.session.courses %}
                                <li><a href="{% url 'student:select-course' course.id %}">{{ course.short_name }}</a>
                                </li>
                                <li class="divider"></li>
                            {% endfor %}
                        {% else %}
                            <li>Brak przedmiotów</li>
                        {% endif %}
                    </ul>
                </li>
                <li class="{% if nbar == 'projects' %}active{% endif %}">
                    <a href="{% url 'student_projects:projects' %}">
                        <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>&nbsp;
                        Projekty
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav nav navbar-right">
                <li class="{% if nbar == 'inbox' %}active{% endif %}">
                    <a href="{% url 'student_inbox:index' %}">
                        <span class="glyphicon glyphicon-inbox" aria-hidden="true"></span>&nbsp;
                        <span class="badge">
                        {% if request.session.inbox %}
                            ({{ request.session.unread_messages_size }})
                        {% else %}
                            (0)
                        {% endif %}
                         </span>
                    </a>
                </li>

                <li class="{% if nbar == 'team' %}active{% endif %}">
                    <a href="{% url 'student_projects:project-team-view' %}">
                        <span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp;
                        Twój projekt
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'main:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Wyloguj
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block body %}

{% endblock %}

</body>
</html>

student/templates/student/index.html
{% extends 'student/base.html' %}

{% block body %}
    <div class="albums-container container-fluid">

        <div class="row">
            <div class="col-sm-12">
                <h3>Zalogowany jako student: {{ user.username }} </h3>
            </div>
        </div>

    </div>

    {% if posts %}
        {% for post in posts %}
            <div class="col-sm-12">
                <div class="thumbnail">
                    <div class="caption">
                        <h1>{{ post.title }} ( {{ post.course.name }} )</h1>
                        <p>{{ post.content }}</p>
                        <div>
                       <span class="badge badge-success">Autor: {{ post.tutor.profile.last_name }} {{ post.tutor.profile.first_name }} -- Post
                            dodany: {{ post.creation_time }}</span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}