main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'

urlpatterns = [
    # /zpr/
    url(r'^$', views.LoginView.as_view(), name='login'),

    url(r'register/$', views.UserFormView.as_view(), name='register'),

    url(r'login/$', views.LoginView.as_view(), name='login'),

    url(r'logout/$', views.LogoutView.as_view(), name='logout'),
]

tutor/urls.py
from django.conf.urls import url, include

from main.methods import select_course
from . import views

app_name = 'tutor'

urlpatterns = [
    # /tutor/
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^select_course/(?P<course_id>[0-9]+)/$', select_course, name='select-course'),

]

tutor_courses/urls.py
from django.conf.urls import url

from tutor_courses.views import assignTutorToCourse
from . import views

app_name = 'tutor_courses'

urlpatterns = [
    url(r'^$', views.CoursesView.as_view(), name='index'),
    url(r'add/$', views.CourseCreate.as_view(), name='course-add'),
    url(r'(?P<pk>[0-9]+)/assign$', assignTutorToCourse, name='course-assing'),
]

tutor_posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'tutor_posts'

urlpatterns = [
    # /tutor/posts/add
    url(r'add/$', views.PostCreate.as_view(), name='post-add'),
    # /tutor/posts/{id}/delete
    url(r'(?P<pk>[0-9]+)/delete/$', views.PostDelete.as_view(), name='post-delete'),
]

tutor_tutors/urls.py
from django.conf.urls import url

from tutor_tutors import views
from tutor_tutors.views import CreateTutor

app_name = 'tutor_tutors'

urlpatterns = [
    url(r'^$', views.TutorsView.as_view(), name='index'),
    url(r'add/$', CreateTutor.as_view(), name='tutor-add'),
    url(r'(?P<pk>[0-9])/delete$', views.DeleteTutor.as_view(), name='tutor-delete'),

]

zpr/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^zpr/', include('main.urls')),
    url(r'^zpr/student/', include('student.urls')),
    url(r'^zpr/student/projects/', include('student_projects.urls')),
    url(r'^zpr/student/inbox/', include('student_inbox.urls')),
    url(r'^zpr/tutor/', include('tutor.urls')),
    url(r'^zpr/tutor/posts/', include('tutor_posts.urls')),
    url(r'^zpr/tutor/projects/', include('tutor_projects.urls')),
    url(r'^zpr/tutor/students/', include('tutor_students.urls')),
    url(r'^zpr/tutor/courses/', include('tutor_courses.urls')),
    url(r'^zpr/tutor/tutors/', include('tutor_tutors.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutor/models.py
from django.db import models

from main.models import UserProfile, Course, Project
from student.models import ProjectTeam


class TutorUser(models.Model):
    profile = models.ForeignKey(UserProfile)
    courses = models.ManyToManyField(Course)
    is_admin = models.BooleanField(default=False)

    class Meta:
        db_table = 'tutor_user'

    def getTutorCourseByCourseId(self, selectedCourseId):
        for tutorCourse in self.tutorcourse_set.all():
            if tutorCourse.courseId == selectedCourseId:
                return tutorCourse
        tutorCourse = TutorCourse(tutor=self, courseId=selectedCourseId, allowedTeamsNumber=10)
        return tutorCourse

    def getTutorAllowedTeamsNumberByCourseId(self,courseId):
        return self.getTutorCourseByCourseId(courseId).allowedTeamsNumber

    def getAllTeamsAssignedToTutorForCourse(self, courseId):
        tutorTeams = []
        allTutorProjects = Project.objects.filter(tutor=self, course=courseId)
        for project in allTutorProjects:
            try:
                tutorTeams.append(ProjectTeam.objects.get(project=project, accepted=True))
            except ProjectTeam.DoesNotExist:
                pass
        return tutorTeams


class TutorCourse(models.Model):
    tutor = models.ForeignKey(TutorUser)
    courseId = models.IntegerField()
    allowedTeamsNumber = models.IntegerField(default=10)

tutor/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View

from main.permissions import has_tutor_permissions
from main_posts.models import Post
from tutor.methods import getTutorUserFromRequest


class IndexView(View):
    template_name = 'tutor/index.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if has_tutor_permissions(request.user):
            tutor = getTutorUserFromRequest(request)
            if tutor.is_admin:
                request.session['isAdmin'] = True
            return super(IndexView, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseForbidden('User has no access rights for viewing this page')

    def get(self, request):
        posts = []
        selectedCourseId = request.session.get('selected_course_id')
        if selectedCourseId is not None:
            try:
                posts = Post.objects.filter(course=selectedCourseId).order_by('-creation_time')
            except Post.DoesNotExist:
                pass
        else:
            posts = Post.objects.all().order_by('-creation_time')

        tutor = getTutorUserFromRequest(request)
        tutorCourses= tutor.courses.all()
        request.session['courses'] = tutorCourses
        return render(request, self.template_name, {'posts': posts})

tutor/templates/tutor/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ZPR</title>
    <!-- Loads the path you static files -->
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}"/>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'tutor:index' %}">{% if request.session.selected_course_shortname %}{{ request.session.selected_course_shortname }}{% else %}Wybierz przedmiot{% endif %}</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Wybór przedmiotu<span
                            class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        {% if request.session.courses %}
                            {% for course in request.session.courses %}
                                <li><a href="{% url 'tutor:select-course' course.id %}">{{ course.short_name }}</a></li>
                                <li class="divider"></li>
                            {% endfor %}
                        {% else %}
                            <li>Brak przedmiotów</li>
                        {% endif %}
                    </ul>
                </li>
                <li class="{% if nbar == 'projects' %}active{% endif %}">
                    <a href="{% url 'tutor_projects:projects' %}">
                        <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>&nbsp;
                        Projekty
                    </a>
                </li>
                <li class="{% if nbar == 'students' %}active{% endif %}">
                    <a href="{% url 'tutor_students:index' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                        Studenci
                    </a>
                </li>
                <li class="{% if nbar == 'courses' %}active{% endif %}">
                    <a href="{% url 'tutor_courses:index' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;
                        Przedmioty
                    </a>
                </li>
                {% if request.session.isAdmin %}
                    <li class="{% if nbar == 'tutors' %}active{% endif %}">
                        <a href="{% url 'tutor_tutors:index' %}">
                            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;
                            Prowadzący
                        </a>
                    </li>
                {% endif %}
            </ul>

            <ul class="nav navbar-nav nav navbar-right">
                <li class="">
                    <a href="{% url 'main:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Wyloguj
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block body %}

{% endblock %}

</body>
</html>

tutor/templates/tutor/index.html
{% extends 'tutor/base.html' %}

{% block body %}
    <div class="albums-container container-fluid">

        <div class="row">
            <div class="col-sm-12">
                <h3>Zalogowany jako: {{ user.username }} </h3>
                <h4> Wybrany przedmiot:
                    {% if request.session.selected_course_shortname %}{{ request.session.selected_course_shortname }}
                    {% else %}Brak wybranego przedmiotu{% endif %}</h4>
            </div>
        </div>

    </div>
    <br>
    <a href="{% url 'tutor_posts:post-add' %}">
        <button type="button" class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>&nbsp; Dodaj nowy post
        </button>
    </a> <br><br>


    {% if posts %}
        {% for post in posts %}
            <div class="col-sm-12">
                <div class="thumbnail">
                    <div class="caption">
                        <h1>{{ post.title }} ( {{ post.course.name }} )</h1>
                        <p>{{ post.content }}</p>
                        <div>
                       <span class="badge badge-success">Autor: {{ post.tutor.profile.last_name }} {{ post.tutor.profile.first_name }} -- Post
                            dodany: {{ post.creation_time }}</span>
                        </div>
                        <!-- Delete Album -->
                        {% if post.tutor.profile.user_id == request.user.id %}
                            <form action="{% url 'tutor_posts:post-delete' post.id %}" method="post"
                                  style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value="{{ post.id }}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
    {% endif %}
{% endblock %}