student/urls.py
from django.conf.urls import url

from main.methods import select_course
from . import views

app_name = 'student'

urlpatterns = [
    # /student/
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^select_course/(?P<course_id>[0-9]+)/$', select_course, name='select-course'),

]

tutor_students/urls.py
from django.conf.urls import url

from tutor_students.views import CreateStudent, read_students_from_file, delete_all_students
from . import views

app_name = 'tutor_students'

urlpatterns = [
    url(r'^$', views.StudentsView.as_view(), name='index'),


    url(r'^read_students_from_file/$', read_students_from_file, name='read_students_from_file'),
    #
    url(r'add/$', CreateStudent.as_view(), name='student-add'),
    url(r'delete-all/$', delete_all_students, name='delete-all'),
    url(r'(?P<pk>[0-9]+)/update$', views.UpdateStudent.as_view(), name='student-update'),
    url(r'(?P<pk>[0-9]+)/delete$', views.DeleteStudent.as_view(), name='student-delete'),

]

zpr/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^zpr/', include('main.urls')),
    url(r'^zpr/student/', include('student.urls')),
    url(r'^zpr/student/projects/', include('student_projects.urls')),
    url(r'^zpr/student/inbox/', include('student_inbox.urls')),
    url(r'^zpr/tutor/', include('tutor.urls')),
    url(r'^zpr/tutor/posts/', include('tutor_posts.urls')),
    url(r'^zpr/tutor/projects/', include('tutor_projects.urls')),
    url(r'^zpr/tutor/students/', include('tutor_students.urls')),
    url(r'^zpr/tutor/courses/', include('tutor_courses.urls')),
    url(r'^zpr/tutor/tutors/', include('tutor_tutors.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/models.py
from django.db import models

from main.models import Project, Course, UserInbox


class ProjectTeam(models.Model):
    project = models.ForeignKey(Project)
    accepted = models.BooleanField(default=False)
    course = models.ForeignKey('main.Course', null=True)


class StudentUser(models.Model):
    profile = models.ForeignKey('main.UserProfile')
    album_number = models.CharField(max_length=16)
    eres_id = models.CharField(max_length=16)
    status = models.BooleanField
    group = models.CharField(max_length=32)
    courses = models.ManyToManyField(Course)
    projectTeams = models.ManyToManyField(ProjectTeam)
    signedProjects = models.ManyToManyField('main.Project')

    class Meta:
        db_table = 'student_user'

    def getCourseById(self, courseId):
        for course in self.courses.all():
            if course.id == courseId:
                return course
        return None

    def getSignedProjectForCourse(self, courseId):
        for project in self.signedProjects.all():
            if project.course.id == courseId:
                return project
        return None

    def setSignedProjectForCourse(self, project, courseId):
        alreadySignedProject = self.getSignedProjectForCourse(courseId)
        if alreadySignedProject is not None:
            self.signedProjects.remove(alreadySignedProject)
        self.signedProjects.add(project)
        self.save()

    def removeSignedProjectForCourse(self, courseId):
        alreadySignedProject = self.getSignedProjectForCourse(courseId)
        if alreadySignedProject is not None:
            self.signedProjects.remove(alreadySignedProject)
            self.save()

    def getProjectTeamForCourse(self, courseId):
        for team in self.projectTeams.all():
            if team.course.id == courseId:
                return team
        return None

    def setProjectTeamForCourse(self, projectTeam, courseId):
        alreadyAssignedProjectTeam = self.getProjectTeamForCourse(courseId)
        if alreadyAssignedProjectTeam is not None:
            self.projectTeams.remove(alreadyAssignedProjectTeam)
        self.projectTeams.add(projectTeam)
        self.save()

    def removeProjectTeamForCourse(self, courseId):
        alreadyAssignedProjectTeam = self.getProjectTeamForCourse(courseId)
        if alreadyAssignedProjectTeam is not None:
            self.projectTeams.remove(alreadyAssignedProjectTeam)
            self.save()

    def isStudentSignedToCourseProjectTeam(self, courseId):
        alreadyAssignedProjectTeam = self.getProjectTeamForCourse(courseId)
        if alreadyAssignedProjectTeam is not None and alreadyAssignedProjectTeam.accepted:
            return True
        else:
            return False

    def getStudentInboxOrCreateIfNone(self):
        if self.profile.inbox is None:
            UserInbox.objects.get_or_create(user_profile=self.profile)
            inbox = UserInbox.objects.get(user_profile=self.profile)
            self.profile.inbox = inbox
            self.profile.save()
        return self.profile.inbox

tutor_students/forms.py
from django import forms


class StudentForm(forms.Form):

    album_number = forms.CharField(max_length=16, label="Nr albumu")
    group = forms.CharField(max_length=32,label="Grupa")
    first_name = forms.CharField(max_length=32,label="Imię")
    last_name = forms.CharField(max_length=32,label="Nazwisko")

student/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View

from main.permissions import has_student_permissions
from main_posts.models import Post
from student.methods import getStudentUserFromRequest
from student_inbox.methods import refreshInboxStatus


class IndexView(View):
    template_name = 'student/index.html'
    login_url = 'main:login'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if has_student_permissions(request.user):
            return super(IndexView, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseForbidden('User has no access rights for viewing this page')

    def get(self, request):
        posts = []
        selectedCourseId = request.session.get('selected_course_id')
        if selectedCourseId is not None:
            try:
                posts = Post.objects.filter(course=selectedCourseId).order_by('-creation_time')
            except Post.DoesNotExist:
                pass
        else:
            posts = Post.objects.all().order_by('-creation_time')

        student = getStudentUserFromRequest(request)
        studentCourses = student.courses.all()
        request.session['courses'] = studentCourses
        refreshInboxStatus(request, student)
        return render(request, self.template_name, {'nbar': 'home', 'posts': posts})

tutor_students/views.py
import csv
import json
import os
import re
from io import TextIOWrapper
from sqlite3 import IntegrityError

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views import View

from main.methods import delayErrorAlertFade, setWrongFileSessionParam, isFileCorrect
from main.models import MyUser, UserProfile, Course
from main.permissions import has_tutor_permissions
from main.views import uniqueContraintValidationRedirect
from student.models import StudentUser
from tutor_students.forms import StudentForm
from tutor_students.methods import addStudentToSelectedCourse, createNewStudentUser, createNewUserProfile, createMyUser, \
    createSystemUser, setNotAddedStudentsRequestParam
from getJson import getJson


class StudentsView(View):
    template_name = 'tutor_students/students_index.html'
    index_template = 'tutor/index.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if has_tutor_permissions(request.user):
            return super(StudentsView, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseForbidden('User has no access rights for viewing this page')

    def get(self, request):
        delayErrorAlertFade(request, 'wrongFile')
        selected_course_id = request.session.get('selected_course_id')
        if (selected_course_id is not None):
            course_students = StudentUser.objects.filter(courses__in=[selected_course_id])
            return render(request, self.template_name, {'nbar': 'students', 'course_students': course_students})
        else:
            return redirect('tutor:index')


class CreateStudent(View):
    form_class = StudentForm
    template_name = 'tutor_students/student_form.html'

    def get(self, request):
        form = StudentForm()
        return render(request, self.template_name, {'nbar': 'students', 'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        notAddedStudents = []
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            album_number = form.cleaned_data['album_number']
            group = form.cleaned_data['group']

            try:
                user = createSystemUser(first_name, last_name, album_number)
                if (user is not None):
                    myUser = createMyUser(user)
                    profile = createNewUserProfile(myUser)
                    createNewStudentUser(profile, album_number, group, request)
                else:
                    if (not addStudentToSelectedCourse(album_number, request)):
                        notAddedStudents.append(first_name + ' ' + last_name)
            except IntegrityError as e:
                return uniqueContraintValidationRedirect(self, request, form)

        setNotAddedStudentsRequestParam(notAddedStudents, request)
        return redirect('tutor_students:index')


class UpdateStudent(View):
    form_class = StudentForm
    template_name = 'tutor_students/student_form.html'

    def get(self, request, pk):
        student_id = request.GET['student_id']
        if (student_id is not None):
            student = get_object_or_404(StudentUser, id=student_id)
            form = StudentForm(
                {'album_number': student.album_number, 'group': student.group, 'first_name': student.profile.first_name,
                 'last_name': student.profile.last_name})
            form.fields['first_name'].widget.attrs['readonly'] = True
            form.fields['last_name'].widget.attrs['readonly'] = True
            return render(request, self.template_name, {'nbar': 'students', 'form': form})
        else:
            return redirect('tutor_students:index')

    def post(self, request, pk):
        form = self.form_class(request.POST)

        if form.is_valid():
            student_id = pk
            if (student_id is not None):
                student = get_object_or_404(StudentUser, id=student_id)
                album_number = form.cleaned_data['album_number']
                group = form.cleaned_data['group']
                student.album_number = album_number
                student.group = group
                try:
                    student.save()
                except IntegrityError as e:
                    return uniqueContraintValidationRedirect(self, request, form)

        return redirect('tutor_students:index')


class DeleteStudent(View):
    def post(self, request, pk):
        student_id = request.POST['student_id']

        if student_id is not None:
            student = get_object_or_404(StudentUser, id=student_id)
            profile = get_object_or_404(UserProfile, id=student.profile.id)
            myUser = get_object_or_404(MyUser, id=profile.user.id)
            user = get_object_or_404(User, id=myUser.user.id)

            try:
                student.delete()
                profile.delete()
                myUser.delete()
                user.delete()
            except User.DoesNotExist:
                messages.error(request, "User does not exist")
                return render(request, 'tutor_students/students_index.html', {'nbar': 'students'})

            except Exception as e:
                return render(request, 'tutor_students/students_index.html', {'nbar': 'students', 'errors': e})

        return redirect('tutor_students:index')


def read_students_from_file(request):
    request.session['notAddedStudents'] = None
    if isFileCorrect('students_file', '.csv', request):
        notAddedStudents = []
        fileDest = saveFile(request)
        parsedStudentsJson = getJson.parseFile(fileDest)
        os.remove(settings.MEDIA_ROOT + "studenci.csv")
        parsedStudents = json.loads(parsedStudentsJson)
        addedStudents = []
        for student in parsedStudents["Data"]:
            first_name = student["Imiona"].split(' ', 1)[0]
            last_name = student["Nazwisko"]
            album_number = student["Indeks"]
            group = student["Grupa"]

            try:
                user = createSystemUser(first_name, last_name, album_number)
                if user is not None:
                    myUser = createMyUser(user)
                    profile = createNewUserProfile(myUser)
                    createNewStudentUser(profile, album_number, group, request)
                    addedStudents.append(first_name + ' ' + last_name)
                else:
                    addStudentToSelectedCourse(album_number, request)
            except IntegrityError as e:
                notAddedStudents.append([first_name + ' ' + last_name])
                pass
        if notAddedStudents.__len__() > 0:
            setNotAddedStudentsRequestParam(notAddedStudents, request)
        return redirect('tutor_students:index')
    else:
        setWrongFileSessionParam(request)
        return redirect('tutor_students:index')



def delete_all_students(request):
    selectedCourseId = request.session.get('selected_course_id')
    course = Course.objects.get(id=selectedCourseId)
    for student in course.studentuser_set.all():
        student.courses.remove(course)
        student.save()

    request.session['notAddedStudents'] = None
    return redirect('tutor_students:index')

def saveFile(request):
    with open(settings.MEDIA_ROOT + "studenci.csv", 'wb+') as destination:
        for chunk in request.FILES['students_file'].chunks():
            destination.write(chunk)
        return destination.name

tutor_students/templates/tutor_students/student_form.html
{% extends 'tutor/base.html' %}
{% block title %}Dodaj nowy projekt{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                           {{ form.as_p }}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Dodaj studenta</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

tutor_students/templates/tutor_students/students_index.html
<!DOC{% extends 'tutor/base.html' %}
{% block title %}Studenci{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                {% if request.session.wrongFile %}
                    <div class="alert alert-warning">
                        {{ request.session.wrongFile }}
                    </div>
                {% endif %}
                <form class="form-horizontal" action="{% url 'tutor_students:read_students_from_file' %}"
                      method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="students_file"/>
                    <br>
                    <div class="form-group">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-success">Wczytaj studentów z pliku</button>
                        </div>
                    </div>
                </form>

                <a href="{% url 'tutor_students:student-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Dodaj studenta manualnie
                    </button>
                </a> <br><br>
                <a href="{% url 'tutor_students:delete-all' %}">
                    <button type="button" class="btn btn-danger">
                        <span class="glyphicon glyphicon-remove-sign"></span>&nbsp;Wyczyść listę studentów
                    </button>
                </a> <br><br>
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% if request.session.notAddedStudents %}
                            <div class="alert alert-warning">
                                Niektórzy studenci nie zostali dodani ponieważ już istnieją w systemie:<br>
                                {% for notAdded in request.session.notAddedStudents %}
                                    {{ notAdded }}<br>
                                {% endfor %}
                            </div>
                        {% endif %}
                        <div class="thumbnail caption">
                            Lista studentów
                        </div>
                        <hr>
                        {% if course_students %}
                            {% for student in course_students %}
                                <div class="caption">
                                    Login użytkownika: {{ student.profile.username }}<br><br>
                                    Nr albumu: {{ student.album_number }} <br><br>
                                    Imię i
                                    nazwisko: {{ student.profile.first_name }} {{ student.profile.last_name }}<br><br>
                                    Grupa: {{ student.group }}<br><br>
                                    <!-- Delete Project -->
                                    <form action="{% url 'tutor_students:student-delete' student.id %}" method="post"
                                          style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="student_id" value="{{ student.id }}"/>
                                        <button type="submit" class="btn btn-default btn-sm" id="deleteUserButton">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>

                                    <form action="{% url 'tutor_students:student-update' student.id %}" method="get"
                                          style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="student_id" value="{{ student.id }}"/>
                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-edit"></span>
                                        </button>
                                    </form>
                                </div><br>
                                <hr>
                            {% endfor %}
                        {% endif %}


                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}