tutor_projects/urls.py
from django.conf.urls import url

from tutor_projects.views import read_projects_from_file, vacate_project, \
    minusTutorAllowedTeamsNumber, plusTutorAllowedTeamsNumber, delete_all_projects
from . import views

app_name = 'tutor_projects'

urlpatterns = [
    url(r'^$', views.ProjectsView.as_view(), name='projects'),


    url(r'^read_projects_from_file/$', read_projects_from_file, name='read_projects_from_file'),

    url(r'add/$', views.ProjectCreate.as_view(), name='project-add'),
    url(r'(?P<pk>[0-9]+)/update$', views.ProjectUpdate.as_view(), name='project-update'),
    url(r'(?P<pk>[0-9]+)/delete$', views.ProjectDelete.as_view(), name='project-delete'),
    url(r'(?P<pk>[0-9]+)/vacate$', vacate_project, name='project-vacate'),
    url(r'teamsNumber/plus$', plusTutorAllowedTeamsNumber, name='project-teams-plus'),
    url(r'teamsNumber/minus$', minusTutorAllowedTeamsNumber, name='project-teams-minus'),
    url(r'deleteAll/$', delete_all_projects, name='delete-all'),

]

zpr/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^zpr/', include('main.urls')),
    url(r'^zpr/student/', include('student.urls')),
    url(r'^zpr/student/projects/', include('student_projects.urls')),
    url(r'^zpr/student/inbox/', include('student_inbox.urls')),
    url(r'^zpr/tutor/', include('tutor.urls')),
    url(r'^zpr/tutor/posts/', include('tutor_posts.urls')),
    url(r'^zpr/tutor/projects/', include('tutor_projects.urls')),
    url(r'^zpr/tutor/students/', include('tutor_students.urls')),
    url(r'^zpr/tutor/courses/', include('tutor_courses.urls')),
    url(r'^zpr/tutor/tutors/', include('tutor_tutors.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/models.py
from django.db import models

from main.models import Project, Course, UserInbox


class ProjectTeam(models.Model):
    project = models.ForeignKey(Project)
    accepted = models.BooleanField(default=False)
    course = models.ForeignKey('main.Course', null=True)


class StudentUser(models.Model):
    profile = models.ForeignKey('main.UserProfile')
    album_number = models.CharField(max_length=16)
    eres_id = models.CharField(max_length=16)
    status = models.BooleanField
    group = models.CharField(max_length=32)
    courses = models.ManyToManyField(Course)
    projectTeams = models.ManyToManyField(ProjectTeam)
    signedProjects = models.ManyToManyField('main.Project')

    class Meta:
        db_table = 'student_user'

    def getCourseById(self, courseId):
        for course in self.courses.all():
            if course.id == courseId:
                return course
        return None

    def getSignedProjectForCourse(self, courseId):
        for project in self.signedProjects.all():
            if project.course.id == courseId:
                return project
        return None

    def setSignedProjectForCourse(self, project, courseId):
        alreadySignedProject = self.getSignedProjectForCourse(courseId)
        if alreadySignedProject is not None:
            self.signedProjects.remove(alreadySignedProject)
        self.signedProjects.add(project)
        self.save()

    def removeSignedProjectForCourse(self, courseId):
        alreadySignedProject = self.getSignedProjectForCourse(courseId)
        if alreadySignedProject is not None:
            self.signedProjects.remove(alreadySignedProject)
            self.save()

    def getProjectTeamForCourse(self, courseId):
        for team in self.projectTeams.all():
            if team.course.id == courseId:
                return team
        return None

    def setProjectTeamForCourse(self, projectTeam, courseId):
        alreadyAssignedProjectTeam = self.getProjectTeamForCourse(courseId)
        if alreadyAssignedProjectTeam is not None:
            self.projectTeams.remove(alreadyAssignedProjectTeam)
        self.projectTeams.add(projectTeam)
        self.save()

    def removeProjectTeamForCourse(self, courseId):
        alreadyAssignedProjectTeam = self.getProjectTeamForCourse(courseId)
        if alreadyAssignedProjectTeam is not None:
            self.projectTeams.remove(alreadyAssignedProjectTeam)
            self.save()

    def isStudentSignedToCourseProjectTeam(self, courseId):
        alreadyAssignedProjectTeam = self.getProjectTeamForCourse(courseId)
        if alreadyAssignedProjectTeam is not None and alreadyAssignedProjectTeam.accepted:
            return True
        else:
            return False

    def getStudentInboxOrCreateIfNone(self):
        if self.profile.inbox is None:
            UserInbox.objects.get_or_create(user_profile=self.profile)
            inbox = UserInbox.objects.get(user_profile=self.profile)
            self.profile.inbox = inbox
            self.profile.save()
        return self.profile.inbox

tutor_projects/forms.py
from django import forms
from django.forms import Textarea

from main.models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 15})
        }
        fields = ['name', 'description', 'allowed_teams_number', 'minimum_students_number', 'allowed_students_number']

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Nazwa'
        self.fields['description'].label = 'Opis'
        self.fields['allowed_teams_number'].label = 'Liczba dozwolonych zespołów'
        self.fields['minimum_students_number'].label = 'Minimalna liczba studentów'
        self.fields['allowed_students_number'].label = 'Dozwolona liczba studentów'

tutor_projects/views.py
import csv
from io import TextIOWrapper
from sqlite3 import IntegrityError

import requests
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DeleteView
from django.views.generic import UpdateView

from main.methods import delayErrorAlertFade, isFileCorrect, setWrongFileSessionParam
from main.models import Project, Course
from main.permissions import has_tutor_permissions
from tutor.methods import getTutorUserFromRequest
from tutor_projects.forms import ProjectForm
from tutor_projects.methods import saveProject

class ProjectsView(View):
    template_name = 'tutor_projects/projects_index.html'
    index_template = 'tutor/index.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if has_tutor_permissions(request.user):
            return super(ProjectsView, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseForbidden('User has no access rights for viewing this page')

    def get(self, request):
        delayErrorAlertFade(request, 'wrongFile')
        selectedCourseId = request.session.get('selected_course_id')
        if (selectedCourseId is not None):
            tutor = getTutorUserFromRequest(request)
            tutorCourse = tutor.getTutorCourseByCourseId(selectedCourseId)

            allCourseProjects = Project.objects.filter(course=selectedCourseId)
            return render(request, self.template_name, {'nbar': 'projects', 'course_projects': allCourseProjects,
                                                        'tutorAllowedTeamsNumber': tutorCourse.allowedTeamsNumber})
        else:
            return redirect('tutor:index')


def read_projects_from_file(request):
    if isFileCorrect('projects_file', '.csv', request):
        file = TextIOWrapper(request.FILES['projects_file'].file, encoding='utf-8')
        reader = csv.reader(file, delimiter=',')
        descriptions = []
        for row in reader:
            if (row):
                project = Project()
                project.name = 'Projekt'
                project.description = row
                saveProject(project, request)

        request.session['desc'] = descriptions
        return redirect('tutor_projects:projects')
    else:
        setWrongFileSessionParam(request)
        return redirect('tutor_projects:projects')


class ProjectCreate(View):
    form_class = ProjectForm
    template_name = 'tutor_projects/project_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'nbar': 'projects', 'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            project = form.save(commit=False)

            if project.allowed_teams_number <= 0 or project.minimum_students_number <= 0 or project.allowed_students_number <= 0:
                return render(request, self.template_name,
                              {'nbar': 'projects', 'form': form,
                               'error_message': 'Parametry liczbowe mogą przyjmować jedynie wartości większe od 0!'})
            else:
                try:
                    saveProject(project, request)
                except IntegrityError as e:
                    return render(request, self.template_name,
                                  {'nbar': 'projects', 'form': form, 'error_message': 'Taki projekt już istnieje!'})
            return redirect('tutor_projects:projects')


class ProjectUpdate(UpdateView):
    template_name = 'tutor_projects/project_form.html'
    form_class = ProjectForm
    model = Project
    success_url = reverse_lazy('tutor_projects:projects')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ProjectUpdate, self).dispatch(request, *args, **kwargs)


class ProjectDelete(DeleteView):
    model = Project
    success_url = reverse_lazy('tutor_projects:projects')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ProjectDelete, self).dispatch(request, *args, **kwargs)


def plusTutorAllowedTeamsNumber(request):
    tutor = getTutorUserFromRequest(request)
    tutorCourse = tutor.getTutorCourseByCourseId(request.session.get('selected_course_id'))
    tutorCourse.allowedTeamsNumber += 1
    tutorCourse.save()
    return redirect('tutor_projects:projects')


def minusTutorAllowedTeamsNumber(request):
    tutor = getTutorUserFromRequest(request)
    tutorCourse = tutor.getTutorCourseByCourseId(request.session.get('selected_course_id'))
    if (tutorCourse.allowedTeamsNumber > 0):
        tutorCourse.allowedTeamsNumber -= 1
        tutorCourse.save()
    return redirect('tutor_projects:projects')


def vacate_project(request, pk):
    project = get_object_or_404(Project, id=pk)
    vacateProject(project)
    return redirect('tutor_projects:projects')

def delete_all_projects(request):
    selectedCourseId = request.session.get('selected_course_id')
    course = Course.objects.get(id=selectedCourseId)
    for project in course.project_set.all():
        vacateProject(project)
        project.delete()
    return redirect('tutor_projects:projects')


def vacateProject(project):
    for projectTeam in project.projectteam_set.all():
        for student in projectTeam.studentuser_set.all():
            for studentProjectTeam in student.projectTeams.all():
                if studentProjectTeam == projectTeam:
                    student.removeProjectTeamForCourse(projectTeam.course.id)
                    student.save()
        projectTeam.project = None
        projectTeam.delete()
    project.setProjectAvailable()

tutor_projects/templates/tutor_projects/project_form.html
{% extends 'tutor/base.html' %}
{% block title %}Dodaj nowy projekt{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'main/form-template' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Zatwierdź</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

tutor_projects/templates/tutor_projects/projects_index.html
<!DOC{% extends 'tutor/base.html' %}
{% block title %}Dodawanie projektów{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="row">
                    {% if request.session.wrongFile %}
                        <div class="alert alert-warning">
                            {{ request.session.wrongFile }}
                        </div>
                    {% endif %}
                    <div class="pull-right" style="width: 10%">
                        <div class="thumbnail caption">
                            Maksymalna liczba zespołów<br>
                            <form action="{% url 'tutor_projects:project-teams-minus' %}"
                                  method="post"
                                  style="display: inline;">
                                {% csrf_token %}
                                <button class="btn btn-default btn-number" data-type="minus"
                                        data-field="tutorAllowedTeamsNumber">
                                    <span class="glyphicon glyphicon-minus"></span>
                                </button>
                            </form>
                            <input type="text" name="tutorAllowedTeamsNumber" class="form-control input-number"
                                   value="{{ tutorAllowedTeamsNumber }}" min="0">
                            <form action="{% url 'tutor_projects:project-teams-plus' %}"
                                  method="post"
                                  style="display: inline;">
                                {% csrf_token %}
                                <button class="btn btn-default btn-number" data-type="plus"
                                        data-field="tutorAllowedTeamsNumber">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="pull-left">
                        <form class="form-horizontal" action="{% url 'tutor_projects:read_projects_from_file' %}"
                              method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="file" name="projects_file"/>
                            <br>
                            <div class="form-group">
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-success">Wczytaj projekty z pliku</button>
                                </div>
                            </div>
                        </form>

                        <a href="{% url 'tutor_projects:project-add' %}">
                            <button type="button" class="btn btn-success">
                                <span class="glyphicon glyphicon-plus"></span>&nbsp; Dodaj nowy projekt
                            </button>
                        </a> <br><br>

                        <a href="{% url 'tutor_projects:delete-all' %}">
                            <button type="button" class="btn btn-danger">
                                <span class="glyphicon glyphicon-remove-sign"></span>&nbsp;Wyczyść listę projektów
                            </button>
                        </a> <br><br>
                    </div>
                </div>


                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="thumbnail caption">
                            Lista projektów
                        </div>
                        {% if course_projects %}
                            {% for project in course_projects %}
                                <div class="caption">
                                    Nazwa projektu: {{ project.name }} <br><br>
                                    Opis projektu: {{ project.description }}<br><br>
                                    Liczba dozwolonych zespołów: {{ project.allowed_teams_number }}<br>
                                    Minimalna liczba osób w zespole: {{ project.minimum_students_number }}<br>
                                    Liczba dozwolonych osób w zespole: {{ project.allowed_students_number }}<br>
                                    Status projektu: {% if project.available %}
                                    <div class="label label-success">Dostępny</div>{% else %}
                                    <div class="label label-danger">Zajęty</div>{% endif %}
                                    <br><br>
                                    {% if project.studentuser_set.all %}
                                        <span class="label label-info">Zapisani studenci:</span> <br>
                                        <ul class="list-group">
                                            {% for student in project.studentuser_set.all %}
                                                <li class="list-group-item">{{ student.profile.first_name }} {{ student.profile.last_name }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                    {% if project.available %}
                                        <!-- Delete Project -->
                                        <form action="{% url 'tutor_projects:project-delete' project.id %}"
                                              method="post"
                                              style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="project_id" value="{{ project.id }}"/>
                                            <button type="submit" class="btn btn-default btn-sm">
                                                <span class="glyphicon glyphicon-trash"> Usuń</span>
                                            </button>
                                        </form>

                                        <!-- Edit Project -->
                                        <form action="{% url 'tutor_projects:project-update' project.id %}"
                                              method="get"
                                              style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="project_id" value="{{ project.id }}"/>
                                            <button type="submit" class="btn btn-default btn-sm">
                                                <span class="glyphicon glyphicon-edit"> Edytuj</span>
                                            </button>
                                        </form>
                                    {% endif %}
                                    {% if not project.available %}
                                        <form action="{% url 'tutor_projects:project-vacate' project.id %}"
                                              method="post"
                                              style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="project_id" value="{{ project.id }}"/>
                                            <button type="submit" class="btn btn-default btn-sm">
                                                <span class="glyphicon glyphicon-tree-deciduous"> Zwolnij projekt</span>
                                            </button>
                                        </form>
                                    {% endif %}
                                </div><br>
                                <hr>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}